# do not use "latest" here, if you want this to work in the future
image: docker:latest

stages:
  - build

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - host-musl/
      - lkl/
      - sgx-lkl-musl/
    policy: pull-push

variables:
  # fill those if you have a proxy in your environment

# Use this if your GitLab runner does not use socket binding
services:
  - docker:dind

Build:
  stage: build
  script:
    # build sgx-lkl
    #- ./sgx-lkl-docker.sh -s build
    #- DOCKER_CMD="cd /sgx-lkl && make sim DEBUG=0"
    - docker build --target builder -t lsds/sgx-lkl:build .
    - >
      docker run --rm --privileged=true 
      -v $PWD:/sgx-lkl --volume $SSH_AUTH_SOCK:/ssh-agent --env SSH_AUTH_SOCK=/ssh-agent
      lsds/sgx-lkl:build 
      /bin/bash -c "cd /sgx-lkl && git submodule update --init && make clean && make sim DEBUG=0"
  artifacts:
    paths:
    - build/
    expire_in: 3 month
