
stages:
  - build

.default_cache: &default_cache
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - host-musl/
      - lkl/
      - sgx-lkl-musl/

prepare_submodules:
  image: alpine
  stage: .pre
  cache:
    << : *default_cache
    policy: pull-push
  before_script:
    - apk --no-cache add git
  script:
          #- git submodule sync
          #- mv host-musl host-musl.old
          #- mv lkl lkl.old
          #- mv sgx-lkl-musl sgx-lkl-musl.old
    - rm -f host-musl/.git lkl/.git sgx-lkl-musl/.git
    - git submodule update --init
    - ls -al host-musl/../.git/modules/host-musl || true
    - git status
    - exit 1
    - git submodule update --init

.prepare_docker:
  image: docker:latest
  stage: .pre
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - >
      docker build 
      --pull
      --target builder 
      --tag $CI_REGISTRY_IMAGE:latest 
      --cache-from $CI_REGISTRY_IMAGE:latest
      .
    - docker push $CI_REGISTRY_IMAGE:latest

build_simulation:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  cache:
    << : *default_cache
    policy: pull
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - >
      docker run --rm --privileged=true 
      -v $PWD:/sgx-lkl --volume $SSH_AUTH_SOCK:/ssh-agent
      --env SSH_AUTH_SOCK=/ssh-agent
      $CI_REGISTRY_IMAGE:latest 
      /bin/bash -c "cd /sgx-lkl && make sim DEBUG=0"
  artifacts:
    paths:
    - build/
    - tools/
    expire_in: 3 month

build_hardware:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  cache:
    << : *default_cache
    policy: pull
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - >
      docker run --rm --privileged=true 
      -v $PWD:/sgx-lkl --volume $SSH_AUTH_SOCK:/ssh-agent
      --env SSH_AUTH_SOCK=/ssh-agent
      $CI_REGISTRY_IMAGE:latest 
      /bin/bash -c "cd /sgx-lkl && make DEBUG=0"
  artifacts:
    paths:
    - build/
    - tools/
    expire_in: 3 month

#trigger_build_docker:
#  stage: .post
#  trigger: madana-io/madana-dan-docker
